apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.29.4
    helm:
      releaseName: argocd
      values: |
        server:
          configEnabled: true
          # -- [General Argo CD configuration]
          # @default -- See [values.yaml]
          config:
            # Argo CD instance label key
            application.instanceLabelKey: argocd.argoproj.io/instance
            kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
            kustomize.buildOptions.v4.4.0: --output /tmp
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
