apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
spec:
  project: infra
  source:
    repoURL: https://github.com/inductor/home-k8s-lab.git
    targetRevision: HEAD
    path: manifests/local-path-provisioner
    kustomize:
      version: v4.4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
