apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/inductor/home-k8s-lab.git
    targetRevision: HEAD
    path: manifests/metallb
    # kustomize:
    #   version: v4.4.0
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
