apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  project: infra
  source:
    repoURL: https://github.com/inductor/home-k8s-lab.git
    targetRevision: HEAD
    path: manifests/metrics-server
    kustomize:
      version: v4.4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
